spring:
  application:
    name: read-service
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
    consumer:
        key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "com.ecommerce.library.kafka.event"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/read_service
    username: read_service
    password: read_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
minio:
  url: http://localhost:9000
  access-key: root
  secret-key: password
  bucket-name: ecommerce
server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: Read-Service-API-docs
    serverUrl: http://localhost:${server.port}
    serverName: server dev
    title: Read Service API
    version: 1.0.0
    description: API document
