spring:
  application:
    name: saga-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/ecommerce
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  temporal:
    connection:
      target: localhost:7233
    workers:
      - task-queue: createUserQueue
        workflow-classes:
          - com.ecommerce.saga.saga.workflow.impl.CreateUserWorkFlowImpl
        activity-beans:
          - createUserActivitiesImpl
      - task-queue: approveOwnerQueue
        workflow-classes:
          - com.ecommerce.saga.saga.workflow.impl.ApproveOwnerWorkFlowImpl
        activity-beans:
          - approveOwnerActivitiesImpl

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: Saga-Service-API-docs
    serverUrl: http://localhost:${server.port}
    serverName: server dev
    title: Saga Service API
    version: 1.0.0
    description: API document
