spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/auth/realms/${KEYCLOAK_REALM:ecommerce}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql8}:${MYSQL_PORT:3306}/product_service
    username: product_service
    password: product_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: ${SERVER_PORT:8086}

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:discovery-service}:${DISCOVERY_SERVICE_PORT:8761}/eureka/
